minimumReleaseAgeExcludePrune: true
trustPolicy: no-downgrade
shellEmulator: true

packages:
  - packages/*

allowBuilds:
  esbuild: true
  simple-git-hooks: true

catalogs:
  build:
    tsdown: ^0.23.0
  dev:
    '@typescript-eslint/utils': ^8.70.0
    tinyglobby: ^0.2.17
    typescript: ^6.0.3
    yaml: ^2.9.0
  lint:
    '@antfu/eslint-config': ^9.5.1
    '@eslint/markdown': ^8.0.3
    eslint: 10.10.0
    eslint-factory: ^0.1.2
    eslint-plugin-format: ^2.0.1
    eslint-plugin-md-style: ^0.3.1
    eslint-typegen: ^2.3.1
    eslint-vitest-rule-tester: ^3.2.0
  script:
    bumpp: ^12.3.0
    lint-staged: ^17.5.1
    simple-git-hooks: ^2.14.0
    tsx: ^4.23.13
  test:
    '@vitest/coverage-v8': ^5.0.0
    vitest: ^5.0.0
  types:
    '@types/mdast': ^4.0.4
    '@types/node': ^26.5.1
    '@types/unist': ^3.0.3
